name: Setup project
description: Setup project dependencies
runs:
  using: composite
  steps:
    - name: Setup CI Enviroment Variable
      shell: bash
      run: export CI=true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: "yarn"

    - name: Install project dependencies
      shell: bash
      run: yarn install --frozen-lockfile
