name: Setup project
description: Setup project dependencies
runs:
  using: composite
  steps:
    - name: Setup CI Enviroment Variable
      shell: bash
      run: export CI=true

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: lts/*
        # cache: yarn

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Get yarn cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-


    - name: Install project dependencies
      shell: bash
      run: yarn install --frozen-lockfile
