name: Setup project
description: Setup project with node pnpm docker-buildx
inputs:
  dependencies:
    description: Install dependencies
    required: false
  buildx:
    description: Install docker buildx
    required: false
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org

    - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      if: ${{ inputs.dependencies == 'true' }}
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Setup Bun
      if: ${{ inputs.dependencies == 'true' }}
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

    - name: Install npm dependencies
      if: ${{ inputs.dependencies == 'true' }}
      shell: bash
      run: bun install --frozen-lockfile

    - name: Install docker buildx
      if: ${{ inputs.buildx == 'true' }}
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3
