name: ecomma

networks:
  ecomma:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1

x-common-config: &common
  restart: always
  healthcheck:
    timeout: 5s

x-infras-config: &infras
  <<: *common
  healthcheck:
    interval: 6s
    start_period: 10s
    retries: 10

x-apps-config: &apps
  <<: *common
  env_file: ./infras/.env
  healthcheck:
    interval: 1s
    start_period: 8s
    retries: 120

x-services-config: &services
  <<: *apps
  healthcheck:
    test: wget --spider -q http://127.0.0.1:3000/healthy/readiness

x-csr-site-config: &csr-sites
  <<: *apps
  healthcheck:
    test: wget --spider -q http://127.0.0.1

x-ssr-site-config: &ssr-sites
  <<: *apps
  healthcheck:
    test: wget --spider -q http://127.0.0.1:3000

services:
  nginx:
    <<: *infras
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./infras/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      ecomma:
        ipv4_address: 10.10.10.10
    healthcheck:
      test: wget --spider -q http://127.0.0.1

  mongodb:
    <<: *infras
    build: ./infras/mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      ecomma:
        ipv4_address: 10.10.10.20
    healthcheck:
      test: wget --spider -q http://127.0.0.1:8081

  redis:
    <<: *infras
    build: ./infras/redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      ecomma:
        ipv4_address: 10.10.10.30
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']

  rabbitmq:
    <<: *infras
    build: ./infras/rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
    networks:
      ecomma:
        ipv4_address: 10.10.10.40
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']

  maildev:
    <<: *infras
    build: ./infras/maildev
    container_name: maildev
    ports:
      - 1025:1025
    networks:
      ecomma:
        ipv4_address: 10.10.10.50
    healthcheck:
      test: wget --spider -q http://localhost:1080/healthz

  seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-master
    command: ['master', '-ip=seaweedfs-master', '-port=9333']
    ports:
      - 9333:9333
      - 19333:19333
      - 9324:9324
    networks:
      ecomma:
        ipv4_address: 10.10.10.60
    healthcheck:
      test: wget --spider -q http://seaweedfs-master:9333/cluster/status

  seaweedfs-volume:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-volume
    command:
      [
        'volume',
        '-ip=seaweedfs-volume',
        '-port=8080',
        '-dir=/data',
        '-mserver=seaweedfs-master:9333',
      ]
    ports:
      - '8080:8080'
    depends_on:
      - seaweedfs-master
    networks:
      ecomma:
        ipv4_address: 10.10.10.61
    healthcheck:
      test: wget --spider -q http://seaweedfs-volume:8080/status

  seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-filer
    command: ['filer', '-ip=seaweedfs-filer', '-port=8888', '-master=seaweedfs-master:9333']
    tty: true
    stdin_open: true
    ports:
      - 8888:8888
      - 18888:18888
      - 9326:9326
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
    networks:
      ecomma:
        ipv4_address: 10.10.10.62
    healthcheck:
      test: wget --spider -q http://seaweedfs-filer:8888

  seaweedfs-s3:
    image: chrislusf/seaweedfs:latest
    container_name: seaweedfs-s3
    command:
      ['s3', '-filer=seaweedfs-filer:8888', '-config=/config/config.json', '-ip.bind=0.0.0.0']
    volumes:
      - ./infras/seaweedfs/s3:/config:ro
    ports:
      - 8333:8333
      - 9327:9327
    depends_on:
      - seaweedfs-master
      - seaweedfs-volume
      - seaweedfs-filer
    networks:
      ecomma:
        ipv4_address: 10.10.10.63
    healthcheck:
      test: wget --spider -q http://seaweedfs-s3:8333

  iam-service:
    <<: *services
    image: ebizbase/iam-service:edge
    container_name: iam-service
    networks:
      ecomma:
        ipv4_address: 10.10.10.70

  home-site:
    <<: *ssr-sites
    image: ebizbase/home-site:edge
    container_name: home-site
    networks:
      ecomma:
        ipv4_address: 10.10.10.80

  accounts-site:
    <<: *csr-sites
    image: ebizbase/accounts-site:edge
    container_name: accounts-site
    networks:
      ecomma:
        ipv4_address: 10.10.10.90

  my-account-site:
    <<: *csr-sites
    image: ebizbase/my-account-site:edge
    container_name: my-account-site
    networks:
      ecomma:
        ipv4_address: 10.10.10.100
