services:
  traefik:
    image: 'traefik:v3.2@sha256:efb87236c8c92599bcd3a67a7a8a55e0f255665f4719722bf398935aa9b92270'
    container_name: 'traefik'
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.fbi.com`)
      - traefik.http.routers.traefik.service=traefik@docker
      - traefik.http.services.traefik.loadbalancer.server.port=8080

  mongodb:
    image: ghcr.io/ebizbase/mongodev:latest@sha256:067acd2559e8804320590478ec2b1b108acdd5f8c37e14fc17ff7e35b6cb2abc
    container_name: mongodb
    ports:
      - 27017:27017
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongodb-admin.rule=Host(`mongodb.fbi.com`)
      - traefik.http.routers.mongodb-admin.entrypoints=web
      - traefik.http.services.mongodb-admin.loadbalancer.server.port=8081
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3

  redis:
    image: ghcr.io/ebizbase/redisdev:latest@sha256:71c75f02ae1d4e23d620ac2feae1e51b99945aba68077744956bb77a70166503
    container_name: redis
    ports:
      - 6379:6379
    labels:
      - traefik.enable=true
      - traefik.http.routers.redis-admin.rule=Host(`redis.fbi.com`)
      - traefik.http.routers.redis-admin.entrypoints=web
      - traefik.http.services.redis-admin.loadbalancer.server.port=8081
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq-admin.rule=Host(`rabbitmq.fbi.com`)
      - traefik.http.routers.rabbitmq-admin.entrypoints=web
      - traefik.http.services.rabbitmq-admin.loadbalancer.server.port=15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3

  mailhog:
    image: mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: mailhog
    ports:
      - 1025:1025
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog-admin.rule=Host(`mail.fbi.com`)
      - traefik.http.routers.mailhog-admin.entrypoints=web
      - traefik.http.services.mailhog-admin.loadbalancer.server.port=8025
    healthcheck:
      test: ['CMD', 'wget', '-q', 'http://localhost:8025']
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3

  minio:
    image: quay.io/minio/minio@sha256:1dce27c494a16bae114774f1cec295493f3613142713130c2d22dd5696be6ad3
    container_name: minio
    ports:
      - 9000:9000
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio-admin.rule=Host(`minio.fbi.com`)
      - traefik.http.routers.minio-admin.entrypoints=web
      - traefik.http.services.minio-admin.loadbalancer.server.port=9001
      - traefik.http.routers.minio.rule=Host(`files.fbi.com`)
      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.services.minio.loadbalancer.server.port=9000
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      start_period: 5s
      retries: 3

  mailer-service:
    build:
      dockerfile: Dockerfile.service
      args:
        SERVICE: mailer-service
    container_name: mailer-service
    expose:
      - 3000
    volumes:
      - .:/workspace
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    environment:
      - LOG_DEBUG=*
      - LOG_TRACE=*
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017?directConnection=true
      - RABBITMQ_URIS=amqp://rabbitmq:5672
      - SMTP_URI=smtp://mailhog:1025

  transactional-mailer-service:
    build:
      dockerfile: Dockerfile.service
      args:
        SERVICE: transactional-mailer-service
    container_name: transactional-mailer-service
    expose:
      - 3000
    volumes:
      - .:/workspace
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    environment:
      - LOG_DEBUG=*
      - LOG_TRACE=*
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017?directConnection=true
      - RABBITMQ_URIS=amqp://rabbitmq:5672
      - SMTP_URI=smtp://mailhog:1025
