name: ebizbase
services:
  traefik:
    image: 'traefik:v3.2@sha256:efb87236c8c92599bcd3a67a7a8a55e0f255665f4719722bf398935aa9b92270'
    container_name: traefik
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entryPoints.http.address=:80
    ports:
      - 80:80
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.fbi.com`)
      - traefik.http.routers.traefik.service=traefik@docker
      - traefik.http.services.traefik.loadbalancer.server.port=8080


  mongodb:
    image: ghcr.io/ebizbase/mongodev:latest@sha256:067acd2559e8804320590478ec2b1b108acdd5f8c37e14fc17ff7e35b6cb2abc
    container_name: mongodb
    ports:
      - 27017:27017
    labels:
      - traefik.enable=true
      - traefik.http.routers.mongodb-admin.rule=Host(`mongodb.fbi.com`)
      - traefik.http.routers.mongodb-admin.entrypoints=http
      - traefik.http.services.mongodb-admin.loadbalancer.server.port=8081
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  redis:
    image: ghcr.io/ebizbase/redisdev:latest@sha256:71c75f02ae1d4e23d620ac2feae1e51b99945aba68077744956bb77a70166503
    container_name: redis
    ports:
      - 6379:6379
    labels:
      - traefik.enable=true
      - traefik.http.routers.redis-admin.rule=Host(`redis.fbi.com`)
      - traefik.http.routers.redis-admin.entrypoints=http
      - traefik.http.services.redis-admin.loadbalancer.server.port=8081
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    ports:
      - 5672:5672
    labels:
      - traefik.enable=true
      - traefik.http.routers.rabbitmq-admin.rule=Host(`rabbitmq.fbi.com`)
      - traefik.http.routers.rabbitmq-admin.entrypoints=http
      - traefik.http.services.rabbitmq-admin.loadbalancer.server.port=15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  mailhog:
    image: mailhog/mailhog@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    container_name: mailhog
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailhog-admin.rule=Host(`mail.fbi.com`)
      - traefik.http.routers.mailhog-admin.entrypoints=http
      - traefik.http.services.mailhog-admin.loadbalancer.server.port=8025
    healthcheck:
      test: wget --spider -q http://localhost:8025
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  minio:
    image: quay.io/minio/minio@sha256:1dce27c494a16bae114774f1cec295493f3613142713130c2d22dd5696be6ad3
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ROOT_USER: minioadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio-admin.rule=Host(`minio.fbi.com`)
      - traefik.http.routers.minio-admin.entrypoints=http
      - traefik.http.services.minio-admin.loadbalancer.server.port=9001
      - traefik.http.routers.minio.rule=Host(`files.fbi.com`)
      - traefik.http.routers.minio.entrypoints=http
      - traefik.http.services.minio.loadbalancer.server.port=9000
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  mailer-service:
    build:
      dockerfile: Dockerfile.service
    container_name: mailer-service
    volumes:
      - .:/workspace
    working_dir: /workspace/apps/mailer-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017?directConnection=true
      - RABBITMQ_URIS=amqp://rabbitmq:5672
      - SMTP_URI=smtp://mailhog:1025
      - TRANSACTIONAL_EMAIL_SENDER=Ebizbase<noreply@ebizbase.com>
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailer-service.rule=Host(`mailer-service.fbi.com`)
      - traefik.http.routers.mailer-service.entrypoints=http
      - traefik.http.services.mailer-service.loadbalancer.server.port=3000
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/usr/bin/wget', '--spider', '-q', 'http://127.0.0.1:3000/healthy/readiness']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  iam-service:
    build:
      dockerfile: Dockerfile.service
    container_name: iam-service
    volumes:
      - .:/workspace
    working_dir: /workspace/apps/iam-service
    environment:
      - TOKEN_SECRET=secret
      - ACCESS_TOKEN_EXPIRES=1s
      - REFRESH_TOKEN_EXPIRES=1s
      - MONGODB_URI=mongodb://mongodb:27017?directConnection=true
      - RABBITMQ_URIS=amqp://rabbitmq:5672
      - SMTP_URI=smtp://mailhog:1025
    labels:
      - traefik.enable=true
      - traefik.http.routers.iam-service.rule=Host(`iam-service.fbi.com`)
      - traefik.http.routers.iam-service.entrypoints=http
      - traefik.http.services.iam-service.loadbalancer.server.port=3000
    depends_on:
      mailer-service:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/usr/bin/wget', '--spider', '-q', 'http://127.0.0.1:3000/healthy/readiness']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  home-site:
    build:
      dockerfile: Dockerfile.site
    container_name: home-site
    volumes:
      - .:/workspace
      - ./.angular/deployment:/workspace/.angular
      - ./dist/deployment:/workspace/dist
    environment:
      - PROJECT=home-site
    labels:
      - traefik.enable=true
      - traefik.http.routers.home-site.rule=Host(`fbi.com`)
      - traefik.http.routers.home-site.entrypoints=http
      - traefik.http.services.home-site.loadbalancer.server.port=80
    healthcheck:
      test: ['CMD', '/usr/bin/wget', '--spider', '-q', 'http://127.0.0.1']
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s

  accounts-site:
    build:
      dockerfile: Dockerfile.site
    container_name: accounts-site
    volumes:
      - .:/workspace
      - ./.angular/deployment:/workspace/.angular
      - ./dist/deployment:/workspace/dist
    environment:
      - PROJECT=accounts-site
    labels:
      - traefik.enable=true
      - traefik.http.routers.accounts-site.rule=Host(`accounts.fbi.com`)
      - traefik.http.routers.accounts-site.entrypoints=http
      - traefik.http.services.accounts-site.loadbalancer.server.port=80
    healthcheck:
      test: ['CMD', '/usr/bin/wget', '--spider', '-q', 'http://127.0.0.1']
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 30s
