apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-mongodb
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - name: prepare-mongodb
          image: mongo:8
          command: ['/bin/sh', '-c']
          args:
            - |
              SRC_URI="{{ .Values.prepare.src }}"
              DEST_URI="{{ .Values.mongodb.fullnameOverride }}.{{ .Values.namespace }}.svc.cluster.local"
              TIMEOUT=120 # Thời gian chờ tối đa là 120 giây
              INTERVAL=5   # Kiểm tra kết nối mỗi 5 giây

              # Hàm kiểm tra kết nối MongoDB với timeout
              check_mongo_ready() {
                local uri=$1
                local elapsed=0
                while ! mongosh --eval "db.runCommand({ ping: 1 })" --quiet --host "$uri"; do
                  echo "Waiting for MongoDB at $uri to be ready..."
                  sleep $INTERVAL
                  elapsed=$((elapsed + $INTERVAL))
                  if [ $elapsed -ge $TIMEOUT ]; then
                    echo "Timeout: MongoDB at $uri not ready after $TIMEOUT seconds"
                    exit 1
                  fi
                done
              }

              # Kiểm tra MongoDB nguồn và đích
              check_mongo_ready "$SRC_URI"
              check_mongo_ready "$DEST_URI"

              echo "MongoDB is ready! Starting data copy..."

              # Thực hiện dump và kiểm tra lỗi
              mongodump --uri="$SRC_URI" || { echo "mongodump failed"; exit 1; }

              # Thực hiện restore và kiểm tra lỗi
              mongorestore --uri="$DEST_URI" /dump || { echo "mongorestore failed"; exit 1; }

              echo "Data copy completed successfully!"
          volumeMounts:
            - name: dump-storage
              mountPath: /dump
      restartPolicy: Never
      volumes:
        - name: dump-storage
          emptyDir: {}
