mongodb:
  architecture: replicaset
  replicaCount: 2
  auth:
    enabled: false
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 768Mi
      cpu: 400m


redis:
  architecture: replication
  auth:
    enabled: false
  master:
    resources:
      requests:
        memory: 256Mi
        cpu: 75m
      limits:
        memory: 384Mi
        cpu: 150m
  replica:
    replicaCount: 2
    resources:
      requests:
        memory: 256Mi
        cpu: 75m
      limits:
        memory: 384Mi
        cpu: 150m
