namespace: ecoma-prod

helm:
  releaseName: mongodb
  chart: https://charts.bitnami.com/bitnami/mongodb-16.4.3.tgz
  values:
    architecture: replicaset
    replicaCount: 1
    auth:
      enabled: false
    persistence:
      enabled: true
      size: 10Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 1

