FROM nginx:stable-alpine@sha256:a0ae1fa0e95b9388b3d9489eacc562028e31eab8d4250dfed4348b0b55e6be17

RUN sed -i '1idaemon off;' /etc/nginx/nginx.conf

COPY apps/assets/nginx.development.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx"]
