version: 0.0.1-rc.166
mongodb:
  architecture: replicaset
  replicaCount: 1
  auth:
    enabled: false
  arbiter:
    enabled: false
  persistence:
    enabled: false
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 768Mi
      cpu: 400m
redis:
  architecture: replication
  auth:
    enabled: false
  master:
    resources:
      requests:
        memory: 256Mi
        cpu: 75m
      limits:
        memory: 384Mi
        cpu: 150m
  replica:
    replicaCount: 0
    resources:
      requests:
        memory: 128Mi
        cpu: 75m
      limits:
        memory: 192Mi
        cpu: 150m
