namespace: ecoma-staging

mongodb:
  architecture: standalone
  auth:
    enabled: false # Không bật xác thực cho MongoDB
  fullnameOverride: mongodb

prepare:
  src: mongodb-0.ecoma-prod.svc.cluster.local

redis:
  architecture: standalone
  auth:
    enabled: false # Không bật xác thực cho Redis
  fullnameOverride: redis
