/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace localize {
    export interface ActiveLanguage {
        id?: string;
        code?: string;
        name?: string;
        isDefault?: boolean;
    }
    export interface ActiveLanguagesResponse {
        activeLanguages?: localize.ActiveLanguage[];
    }
    export interface Language {
        id?: string;
        code?: string;
        name?: string;
        isDefault?: boolean;
        isActive?: boolean;
    }
    export interface Languages {
        languages?: localize.Language[];
    }
    export interface UpdateLanguageStatusRequest {
        ids?: string[];
        isActive?: boolean;
    }
    export interface ChangeDefaultLanguageRequest {
        id?: string;
    }
    export interface LocalizeService {
        getActiveLanguages(
            data: google.protobuf.Empty,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<ActiveLanguagesResponse>;
        listLanguages(
            data: common.Listing,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Languages>;
        updateLanguages(
            data: UpdateLanguageStatusRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Languages>;
        changeDefaultLanguage(
            data: ChangeDefaultLanguageRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<google.protobuf.Empty>;
        listTranslations(
            data: common.Listing,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Translations>;
        addTranslations(
            data: Translations,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Translations>;
        updateTranslation(
            data: Translations,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Translations>;
    }
    export interface Translation {
        id?: string;
        service?: string;
        languageCode?: string;
        key?: string;
        value?: string;
    }
    export interface Translations {
        translation?: localize.Translation[];
    }
}
export namespace common {
    export enum ArrayElementOperator {
        ARRAY_ELEMENT_OPERATOR_COUNT = 0,
        ARRAY_ELEMENT_OPERATOR_MATCH = 1,
        ARRAY_ELEMENT_OPERATOR_NOT_MATCH = 2,
        ARRAY_ELEMENT_OPERATOR_REGEX = 3,
    }
    export enum ArrayOperator {
        ARRAY_OPERATOR_IN = 0,
        ARRAY_OPERATOR_NIN = 1,
    }
    export enum ComparisonOperator {
        COMPARISON_OPERATOR_EQ = 0,
        COMPARISON_OPERATOR_NEQ = 1,
        COMPARISON_OPERATOR_GT = 2,
        COMPARISON_OPERATOR_GTE = 3,
        COMPARISON_OPERATOR_LT = 4,
        COMPARISON_OPERATOR_LTE = 5,
    }
    export enum ExistenceOperator {
        EXISTENCE_OPERATOR_EXISTS = 0,
    }
    export enum GeoOperator {
        GEO_OPERATOR_NEAR = 0,
    }
    export enum PatternOperator {
        PATTERN_OPERATOR_LIKE = 0,
        PATTERN_OPERATOR_REGEX = 1,
    }
    export enum RangeOperator {
        RANGE_OPERATOR_BETWEEN = 0,
    }
    export interface ArrayElementFilter {
        field?: string;
        operator?: common.ArrayElementOperator;
        value?: google.protobuf.Any[];
    }
    export interface ArrayFilter {
        field?: string;
        operator?: common.ArrayOperator;
        value?: string[];
    }
    export interface ExistenceFilter {
        field?: string;
        operator?: common.ExistenceOperator;
    }
    export interface GeoFilter {
        field?: string;
        operator?: common.GeoOperator;
        value?: GeoFilter.GeoLocation;
    }
    export namespace GeoFilter {
        export interface GeoLocation {
            lat?: number;
            lng?: number;
            radius?: number;
        }
    }
    export interface PatternFilter {
        field?: string;
        operator?: common.PatternOperator;
        value?: string;
    }
    export interface RangeFilter {
        field?: string;
        operator?: common.RangeOperator;
        value?: number[];
    }
    export interface ComparisonFilter {
        field?: string;
        operator?: common.ComparisonOperator;
        stringValue?: string;
        numberValue?: number;
    }
    export interface Filter {
        arrayElementFilter?: common.ArrayElementFilter;
        arrayFilter?: common.ArrayFilter;
        existenceFilter?: common.ExistenceFilter;
        geoFilter?: common.GeoFilter;
        patternFilter?: common.PatternFilter;
        rangeFilter?: common.RangeFilter;
        comparisonFilter?: common.ComparisonFilter;
    }
    export interface CompositeFilter {
        operator?: boolean;
        filters?: common.Filter[];
    }
    export interface Pagination {
        cursor?: common.CursorPagination;
        offset?: common.OffsetPagination;
    }
    export interface CursorPagination {
        lastId?: string;
    }
    export interface OffsetPagination {
        page?: number;
        pageSize?: number;
    }
    export enum SortDirection {
        SORT_DIRECTION_ASC = 0,
        SORT_DIRECTION_DESC = 1,
    }
    export interface Sort {
        field?: string;
        direction?: common.SortDirection;
    }
    export interface Listing {
        paging?: common.Pagination;
        singleFilter?: common.Filter;
        compositeFilter?: common.CompositeFilter;
    }
}
export namespace google {
    export namespace protobuf {
        // tslint:disable-next-line:no-empty-interface
        export interface Empty {
        }
        export interface Any {
            type_url?: string;
            value?: Uint8Array;
        }
    }
}

