architecture: replicaset
replicaCount: 1
auth:
  enabled: false
arbiter:
  enabled: false
persistence:
  enabled: false
resources:
  requests:
    memory: 512Mi
    cpu: 300m
  limits:
    memory: 768Mi
    cpu: 450m

