name: Merge Group

on:
  merge_group:
    branches:
      - dev

jobs:

  intergration:
    name: Intergration checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Lint
        run: INPUT_GITHUB_TOKEN=${{ secrets.GH_BOT_TOKEN }} npx nx run-many -t lint test build

  # TODO add automation testing on dev enviroment before merge group

