name: CI/CD

on:
  pull_request_target:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
  merge_group:

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:

  intergration:
    name: Intergration
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release.outputs.releases_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/setup
        with:
          dependencies: true
      # - name: Lint
      #   run: CI=true npx nx run-many -t lint
      # - name: Unit Test
      #   run: CI=true npx nx run-many -t test
      - name: Set release config file
        id: set_config
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "Using release.main.js for main branch"
            echo "::set-output name=config_file::release.main.json"
            echo "::set-output name=target_branch::main"
          else
            echo "Using release.dev.json for non-main branches"
            echo "::set-output name=config_file::release.dev.json"
            echo "::set-output name=target_branch::dev"
          fi
      - name: Release Please
        if: github.event_name == 'push'
        id: release
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          config-file: ${{ steps.set_config.outputs.config_file }}
          target-branch: ${{ steps.set_config.outputs.target_branch }}
          manifest-file: release.manifest.json
