name: Delivery

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:

  delivery:
    name: Build and update staging chart sha
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_BOT_TOKEN }}

      - name: Publish Image
        run: INPUT_GITHUB_TOKEN=${{ secrets.GH_BOT_TOKEN }} npx nx run-many -t build -c publish --parallel=4

      - name: Update staging chart to current git SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
            echo "::group::Configuring Git user"
            git config --global user.email "bot@github.com"
            git config --global user.name "Github Action"
            echo "::endgroup::"

            echo "::group:: commit and push change"
            npx release-it -c release.ts --preRelease=rc
            echo "::endgroup::"


