name: Delivery

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:

  delivery:
    name: Build and update staging chart sha
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_BOT_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          INPUT_GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
            echo "::group::Configuring Git user"
            git config --global user.email "bot@github.com"
            git config --global user.name "Github Action"
            echo "::endgroup::"

            echo "::group::Generating next version and changelog"
            version=$(npx release-it --release-version --preRelease=rc)
            echo "Generated version: $version"
            export VERSION=$version
            echo "::endgroup::"

            echo "::group:: commit and push change"
            yq e ".version = \"$VERSION\"" -i deploy/staging/values.yaml
            yq e ".version = \"$VERSION\"" -i deploy/staging/Chart.yaml
            npx nx run-many -t publish
            npx release-it -c release.ts --preRelease=rc
            echo "::endgroup::"


