name: Intergration

on:
  pull_request_target:
    branches:
      - main
  merge_group:
    branches:
      - main
jobs:

  intergration:
    name: Intergration checks
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Lint
        run: npx nx run-many -t lint --parallel=4

      - name: Unit test
        run: npx nx run-many -t test --parallel=4

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_BOT_TOKEN }}

      - name: E2E testing on local enviroment
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3
        with:
          runCmd: |
            INPUT_GITHUB_TOKEN=${{ secrets.GH_BOT_TOKEN }} npx nx run-many -t build --parallel=4
            npx nx automate e2e
