name: Pull Request

on:
  pull_request_target:
    branches:
      - main
      - dev

jobs:

  intergration:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Lint
        run: npx nx run-many -t lint test build
