name: Push

on:
  push:
    branches:
      - main
      - dev

jobs:
  # build:
  #   name: Building
  #   uses: ./.github/workflows/build.yaml
  #   with:
  #     publish: true

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token:  ${{ secrets.GH_BOT_TOKEN }}

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Create Release
        run: |
          npx auto shipit
