name: Unit test

on:
  workflow_call:

jobs:

  unit-test:
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/setup
      - name: Test
        run: npx nx run-many -t test
