networks:
  local_bridge:
    driver: bridge
    name: goup-network
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.1.1

x-common: &common_settings
  labels:
    - 'project=ebizbase'
    - 'layer=infrastructure'

services:
  dns:
    <<: *common_settings
    container_name: dns
    image: 4km3/dnsmasq:2.85-r2-alpine-3.14
    cap_add:
      - NET_ADMIN
    command: >
      --address=/lacolhost.com/172.16.1.3
      --address=/.lacolhost.com/172.16.1.3
      --address=/localtest.me/172.16.1.3
      --address=/.localtest.me/172.16.1.3
      --address=/fbi.com/172.16.1.3
      --address=/.fbi.com/172.16.1.3
      --cache-size=10240
      --server=8.8.8.8
      --server=1.1.1.1
    networks:
      local_bridge:
        ipv4_address: 172.16.1.2
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 6M
    healthcheck:
      test: ['CMD-SHELL', 'pgrep dnsmasq || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10

  nginx:
    <<: *common_settings
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/http-proxy-header.conf:/etc/nginx/http-proxy-header.conf:ro
      - ./nginx/http-server.conf:/etc/nginx/http-server.conf:ro
      - ../../coverage:/var/html/coverage:ro
    networks:
      local_bridge:
        ipv4_address: 172.16.1.3
    deploy:
      resources:
        limits:
          memory: 64M
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://mail.fbi.com || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10

  minio:
    <<: *common_settings
    container_name: minio
    image: minio/minio
    command: server /data --address ":9000" --console-address ":9001" --quiet
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT: false
    networks:
      local_bridge:
        ipv4_address: 172.16.1.4
    deploy:
      resources:
        limits:
          memory: 96M
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:9000/minio/health/live || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10

  mongo-config:
    <<: *common_settings
    build:
      context: ./mongod
      dockerfile: Dockerfile
      args:
        MONGO_VERSION: 4.4
    container_name: mongo-config
    command: mongod --configsvr --port 27017 --replSet configReplSet --quiet --bind_ip_all
    environment:
      - REPL_NAME=configReplSet
      - NODE_HOST=172.16.1.11
    networks:
      local_bridge:
        ipv4_address: 172.16.1.11
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M

  mongo-shard:
    <<: *common_settings
    build:
      context: ./mongod
      dockerfile: Dockerfile
      args:
        MONGO_VERSION: 4.4
    container_name: mongo-shard
    command: mongod --shardsvr --port 27017 --replSet shardReplSet --quiet --bind_ip_all
    environment:
      - REPL_NAME=shardReplSet
      - NODE_HOST=172.16.1.12
    networks:
      local_bridge:
        ipv4_address: 172.16.1.12
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M

  mongo-router:
    <<: *common_settings
    container_name: mongo-router
    build:
      context: ./mongos
      dockerfile: Dockerfile
      args:
        MONGO_VERSION: 4.4
    command: mongos --port 27017 --configdb configReplSet/172.16.1.11:27017 --quiet --bind_ip_all
    depends_on:
      mongo-config:
        condition: service_healthy
      mongo-shard:
        condition: service_healthy
    environment:
      - SHARD_LIST=shardReplSet/172.16.1.12:27017
    networks:
      local_bridge:
        ipv4_address: 172.16.1.5
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 32M

  mongodb-admin:
    <<: *common_settings
    container_name: mongodb-admin
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_FULLWIDTH_LAYOUT=true
      - ME_CONFIG_BASICAUTH_ENABLED=false
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_MONGODB_URL=mongodb://172.16.1.5?directConnection=true&maxPoolSize=1
    depends_on:
      mongo-router:
        condition: service_healthy
    networks:
      local_bridge:
        ipv4_address: 172.16.1.6
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 32M
    healthcheck:
      test: ['CMD-SHELL', 'nc -z 127.0.0.1 8081 || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10

  redis:
    <<: *common_settings
    container_name: redis
    image: redis:6.2-alpine
    command: ['sh', '-c', 'redis-server --maxmemory 12mb --maxmemory-policy allkeys-lru']
    networks:
      local_bridge:
        ipv4_address: 172.16.1.7
    deploy:
      resources:
        limits:
          memory: 16M
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 10s
      retries: 10

  redis-admin:
    <<: *common_settings
    container_name: redis-admin
    image: erikdubbelboer/phpredisadmin
    environment:
      REDIS_1_HOST: 172.16.1.7
      REDIS_1_NAME: local
    networks:
      local_bridge:
        ipv4_address: 172.16.1.8
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 16M
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10

  rabbitmq:
    <<: *common_settings
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      local_bridge:
        ipv4_address: 172.16.1.9
    deploy:
      resources:
        limits:
          memory: 128M
    command: >
      rabbitmq-server
         --log_levels.default=none
    healthcheck:
      test: ['CMD-SHELL', 'rabbitmq-diagnostics -q ping']
      interval: 10s
      timeout: 10s
      retries: 10

  mailhog:
    <<: *common_settings
    container_name: mailhog
    build: ./mailhog
    networks:
      local_bridge:
        ipv4_address: 172.16.1.10
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 16M
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8025 || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10
